Capstone Project
VicPeralta/ChessEvent pull request #1
Opened 2022-02-01 21:33 UTC by VicPeralta

# HTML/CSS/Javascripts Capstone Project

- No linter errors
- Correct GitHub flow
- Documented in a professional way
- Implemented HomePage and about page
- Mobile version (up to 768px wide)
- Desktop version (from 769px and wider)
- The home page has a link to the about page
- The logo links to the home page
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- The mobile menu is implemented considering the overall design
- The mobile menu contains a close (X) button that closes the menu
- The speaker section is created dynamically in JavaScript
- An array of speaker objects is used to create the speaker's section
Here is the link to the video:
https://www.loom.com/share/e6601cb976ba4b98a02542ce5a8af167

2022-02-01 23:07 UTC, mateo951 requested changes
### Hi @VicPeralta, 

📝👌 **Your project highlights** 🔥😎 
- General Requirements 👌
- JS Implementations! Your speakers addition was super good 😎

I had a great time reviewing your project 🧐 You have done a splendid job with your capstone this week 🔥 You just need to address a few issues and you will be good to go ✔

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-01 23:07 UTC, mateo951 commented on README.md
> +[Original design idea by Cindy Shin in Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
You gave the propper mention to the artist ✔

2022-02-01 23:07 UTC, mateo951 commented on README.md
> +[Live demo](https://vicperalta.github.io/capstoneHTMLJS/)
Live version is working as expected 😎

2022-02-01 23:07 UTC, mateo951 commented on index.html
> +      </nav>
Page Structure and Navigation 🔥
  - You have a  `Home` and `About` page
  - Navigation works correctly

2022-02-01 23:07 UTC, mateo951 commented on index.html
> +      </nav>
It is important to follow the design as much as possible to meet the project requirements 🤓 It is important to show a visual distinction between the navbar with a bottom white/gray bar/line as you can see in the following images. Your mobile design is perfect because you have the chess photo and the hamburger button and the previously mentioned distinction is not necessary. The issue resides in the desktop size. Please add the necessary bottom bar/line so we follow the design 🔥

![image](https://user-images.githubusercontent.com/15807343/152063896-4e980f76-3e13-4072-9c3d-e12775d93ccf.png)


![image](https://user-images.githubusercontent.com/15807343/152063719-2ab3ec3c-6e66-4d08-8ecd-5e901d88a1bd.png)

2022-02-01 23:07 UTC, mateo951 commented on index.html
> +        <h1 class="event-title">CAPABLANCA<br>MEMORIAL FAIR <br> 2022</h1>
There's a small issue with the main title size on your desktop design. As you can see in the following image, this `h1` tag should be a lot bigger than its actual size. Please play with your .event-title class in order to make your website almost identical to the design as it is the intention of the project 🤓 You could also resize a bit the 'Hello!' `p` tag above

### Figma's Design 
![image](https://user-images.githubusercontent.com/15807343/152064902-d189a826-d8fd-4723-a8e0-e610812106bc.png)

### Your Design 
![image](https://user-images.githubusercontent.com/15807343/152065377-013899b0-114b-4609-8a43-847a3ebf8e7c.png)

2022-02-01 23:07 UTC, mateo951 commented on index.html
> +  <section class="welcome" id="home">
Correct use of semantic tags 😉

2022-02-01 23:07 UTC, mateo951 commented on program.css
> +@media (min-width: 769px) {
The CSS styling is built as **mobile-first**, media queries are used to change the design from mobile to desktop, not the other way around 😎🔥

2022-02-01 23:07 UTC, mateo951 commented on speakers.js
> +fillSpeakerSection(speakersInfo);
The section "Featured speakers" is generated dynamically with JavaScript ✔

2022-02-01 23:07 UTC, mateo951 commented on speakers.js
> +];
Each speaker object contains all the information needed to generate the dynamic element 😎

2022-02-01 23:08 UTC, mateo951 commented
Your video covers all the expected details of your project including a portion of your project you are proud of 😎 You did great work explaining it clearly!

2022-02-01 23:48 UTC, VicPeralta commented on index.html
> +        <h1 class="event-title">CAPABLANCA<br>MEMORIAL FAIR <br> 2022</h1>
Thanks for the suggestion. I make the text bigger and definitely looks way better

2022-02-01 23:49 UTC, VicPeralta commented on index.html
> +      </nav>
The desktop version contains a background image but it is too light. I added the gray bar and also updated the background image for another one a little darker.

2022-02-02 00:00 UTC, julie-ify approved these changes
## Hi @VicPeralta, 

# Highlights
- Good job implementing the suggested changes from the previous reviewer ✔️ 
- Good video presentation ✔️ 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![Approved emoji](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 00:01 UTC, merged